config/routes.rb
Rails.application.routes.draw do

  resources :log_in

  resources :users

  resources :exercises 

  resources :categories 

  resources :exercisecategories
  
 

  resources :workouts 


end
 

# 5.) How can I make a delete button for a specific workout?


# 3.) Where do I make a delete button?  

# 4.) Why doesnt the user login not direct to user show page, or 
#     does it matter if its the show or index page 

#7.) why doesnt it show the specific users workouts, and edit page 
#instead of all of them












# _____
# 1.) how to I seperate my workouts 

# 2.) how do I make my back button work 

#6.) do I need the drop down menu of the users? or
#should the workouts already be created and edited under my user?

#8.) Why dont my associtions work ?

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  validates_numericality_of :reps, :sets, greater_than_or_equal_to: 1, less_than_or_equal_to: 25, message: 'must be between 1 & 25'
  validates_presence_of :name, :sets, :reps, :intensity, message: 'Blank entry not valid'
end

app/models/category.rb
class Category < ApplicationRecord
has_many :exercise_categories
has_many :exercises, through: :exercise_categories
end

app/models/exercise.rb
class Exercise < ApplicationRecord
    
    belongs_to :user
    belongs_to :workout 
    has_many :exercise_categories, dependent: :destroy
    has_many :categories, through: :exercise_categories


 end 

 

app/models/exercise_category.rb
class ExerciseCategory < ApplicationRecord
belongs_to :exercise
belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
has_many :exercises 
has_many :workouts, through: :exercises
has_secure_password
end

app/models/workout.rb
class Workout < ApplicationRecord
has_many :exercises, dependent: :destroy
has_many :users, through: :exercises
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :require_login
    helper_method :current_user
    add_flash_types :info, :error, :warning
    #check current user 
    #logged?
    #require login
    def require_login
        
        unless logged_in?
            redirect_to new_log_in_path
        end 
    end 

    def current_user
        User.find_by(id:session[:user_id])
    end

    def current_user_id
        session[:user_id]
    end 

    def logged_in?
        !!current_user_id
    end 
  
    def log_in_user(user_id)
        session[:user_id] = user_id
    end 
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    
    def index
        @categories = Category.all
    end

    def show
        @category = Category.find(params[:id])
    end

    # def new
    #     @category = Category.new
    # end

    # def create
    #     @category = Category.new(category_params)
    #     if @category.save
    #         redirect_to @category
    #     else 
    #         render :new
    #     end
    # end

    # def edit
    #     @category = Category.find(params[:id])
    # end

    # def update
    #     @category = Category.find(params[:id])
    #     @category.update(category_params
    #     if @category.save
    #         redirect_to
    #     else 
    #         render :edit
    #     end
    # end

    # def destroy
    #     @category = Category.find(params[:id])
    #     @category.destroy
    #     flash[:notice] = "Category has been deleted"
    #     redirect_to category_path 
    # end

    # private

    # def category_params
    #     params.require(:category).permit.(:name)
    # end

end

app/controllers/exercisecategories_controller.rb
class ExercisecategoriesController < ApplicationController

    
 def index
    @exercise_categories = ExerciseCategory.all 
 end

 def show
    @exercise_category = ExerciseCategory.find(params[:id])
 end


 
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
    
 def index
    @exercises = current_user.exercises
 end

 def show
    @exercise = Exercise.find(params[:id])
 end

 def new
    @exercise = Exercise.new
 end

 def create
    @exercise = Exercise.create(exercise_params)
    if @exercise.valid?
      redirect_to user_path(@exercise.user)
   else
      flash[:notice] = "Invalid entry"
      redirect_to new_exercise_path
   end
 end

 def edit
    @exercise = Exercise.find(params[:id])
 end

 def update
    @exercise = Exercise.find(params[:id])
    @exercise.update(exercise_params)
    if @exercise.save
        redirect_to exercises_path
        flash[:notice] = "Your exercise has been successfully updated!"
    else
        render :edit 
    end
 end

 def destroy
    @exercise = Exercise.find(params[:id])
    @exercise.destroy
    flash[:notice] = "Your exercise has been deleted."
    redirect_to exercises_path
 end

 private

 def exercise_params
    params.require(:exercise).permit(:name, :intensity, :sets, :reps, :user_id, :workout_id)
 end

end

app/controllers/log_in_controller.rb
class LogInController < ApplicationController
    skip_before_action :require_login, :only => [:create, :new]
    
    def new
    end 

    def create

        @user = User.find_by(username:params[:log_in][:username])
        if @user && @user.authenticate(params[:log_in][:password])
            log_in_user(@user.id)
            redirect_to user_path(@user)
        else
            redirect_to new_log_in_path, notice: "User not found"
        end 
    end 
end

def index 

end

#do I need to move my user view work to log_in?
#or why does it redirect me back to new_log_in_path

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :require_login, :only => [:create, :new]
    
    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
    end 

    def new
        @user = User.new
    end

    def create
        @user = User.create(user_params)
        if @user.valid?
            log_in_user(@user.id)
            redirect_to user_path(@user)
        else
            flash[:notice] = "No matching account"
            redirect_to new_user_path
        end
    end

    # def edit
    #     @user = User.find(params[:id])
    # end

    # def update
    #     @user = User.find(params[:id])
    #     @user.update(user_params)
    #     if @user.save
    #         redirect_to @user 
    #     else
    #         render :edit 
    #     end
    # end

    # def destroy
    #     @user = User.find(params[:id])
    #     @user.destroy
    #     flash[:notice] = "User has been deleted."
    #     redirect_to users_path 
    # end

    private

    def user_params
        params.require(:user).permit(:username, :password)
    end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController

    def index
        @workouts = Workout.all
    end

    def show
        @workout = Workout.find(params[:id])
    end

    def new
        @workout = Workout.new
    end

    def create
        @workout = Workout.new(workout_params)
        if @workout.save
            redirect_to @workout
        else 
            render :new
        end
    end

    def edit
        @workout = Workout.find(params[:id])
    end

    def update
        @workout = Workout.find(params[:id])
        @workout.update(workout_params)
        if @workout.save 
            redirect_to @workout
        else 
            render :edit
        end
    end

    def destroy
        @workout = Workout.find(params[:id])
        @workout.destroy
        flash[:notice] = "Workout has been deleted"
        redirect_to workout_path 
    end

    private

    def workout_params
        params.require(:workout).permit(:plan, :name, :intensity, :sets, :reps, :categories, :workouts)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/exercisecategories_helper.rb
module ExercisecategoriesHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/exercises/edit.html.erb
<h1> Edit your workout <i class="em em-hammer_and_wrench" aria-role="presentation" aria-label=""></i></h1>
<link href="https://emoji-css.afeld.me/emoji.css" rel="stylesheet">

<%= form_for @exercise do |f| %> 
    <%= f.label :name_of_exercise %> 
    <%= f.text_field :name %>
    <br>
    <br>
    <%= f.label :intensity_of_exercise %>  
    <%= f.text_field :intensity %>
    <br>
    <br>
    <%= f.label :number_of_sets %> 
    <%= f.number_field :sets %>
    <br>
    <br>
    <%= f.label :reps_per_set %> 
    <%= f.number_field :reps %>
    <br>
    <br>
    <%= f.collection_select :workout_id, Workout.all, :id, :plan %>
    <br>
    <br>
    <%= f.collection_select :user_id, User.all, :id, :username %>
    <br>
    <br>
    <%= f.submit %>
    <br>
    <br>
<% end %>
<%= link_to 'Back', user_path %>

app/views/exercises/index.html.erb
<h1> List of your exercises </h1>
<br>
<%= link_to '<<<', user_path(current_user) %>
<br>
<ul>
    <% @exercises.all.each do |f| %>
        <br>
        <li> exercise Name: <%= f.name %></li>
        <br>
        <li> exercise Intensity: <%= f.intensity %></li>
        <br>
        <li> Sets: <%= f.sets %></li>
        <br>
        <li> Reps: <%= f.reps %></li>
        <br>
     
        <%= link_to "EDIT", edit_exercise_path(f) %>
        <br>
        <br>
        <%= button_to "Delete this exercise", f, method: :delete, data: {confirm: "Delete Confirmation"} %>
        <br>
        <br>
    <% end %> 
</ul>

app/views/exercises/new.html.erb
<h1> Create a <i class="em em-new" aria-role="presentation" aria-label="SQUARED NEW"></i> exercise </h1>

<%= form_for @exercise do |f| %> 
    <%= f.label :name_of_exercise %> 
    <%= f.text_field :name %>
    <br>
    <br>
    <%= f.label :intensity_of_exercise %>  
    <%= f.text_field :intensity %>
    <br>
    <br>
    <%= f.label :number_of_sets %> 
    <%= f.number_field :sets %>
    <br>
    <br>
    <%= f.label :reps_per_set %> 
    <%= f.number_field :reps %>
    <br>
    <br>
    <%= f.collection_select :workout_id, Workout.all, :id, :plan %>
    <br>
    <br>
    <%= f.collection_select :user_id, User.all, :id, :username %>
    <br>
    <br>
    <%= f.submit %>
    <br>
    <br>
    <%= link_to 'Back', user_path(current_user) %>
<% end %>

<link href="https://emoji-css.afeld.me/emoji.css" rel="stylesheet">

app/views/log_in/new.html.erb
<div class="container" id="log_in_form">
    <h2>Hello! Welcome to FreedomFitness <i class="em em-zap" aria-role="presentation" aria-label="HIGH VOLTAGE SIGN"></i></h2>
    <%= form_for :log_in , url: log_in_index_path do |f| %>
        <%= f.label :username %>
        <%= f.text_field :username %>
        <br>
        <br>
        <%= f.label :password %>
        <%= f.text_field :password %>
        <br>
        <br>
        <%= f.submit%>
    <% end %>
</div>
<br>
<br>
<%= link_to "Sign up here!", new_user_path %>

<link href="https://emoji-css.afeld.me/emoji.css" rel="stylesheet">

app/views/users/new.html.erb
<div class="container" id="log_in_form" >
<h2> Create new user form.. <i class="em em-zap" aria-role="presentation" aria-label="HIGH VOLTAGE SIGN"></i></h1>
<%= form_with model: @user do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>
    <br>
    <br>
    <%= f.label :password %>
    <%= f.text_field :password %>
    <br>
    <br>
    <%= f.submit "Login" %>
<% end %>
</div>

<link href="https://emoji-css.afeld.me/emoji.css" rel="stylesheet">

app/views/users/show.html.erb
<h1>FreedomFitness <i class="em em-zap" aria-role="presentation" aria-label="HIGH VOLTAGE SIGN"></i></h1>
<link href="https://emoji-css.afeld.me/emoji.css" rel="stylesheet">
<h3>Welcome <%= @user.username%>!</h3>


    <%= link_to "New exercise", new_exercise_path %> 
    <br>
    <br>
    <%= link_to "View Workout", exercises_path %>
    <br>
    <br>
    <%= link_to 'Log out', new_log_in_path %>